version: "3.9"

services:
  frontend:
    image: fahad1000mir/quranity-landing:latest
    container_name: quranity-landing
    ports:
      - "3000:3000"
    # env_file:
    #   - .env
    restart: always
    
    