import Navbar from "./components/Header/Navbar";
import "./globals.css";

export const metadata = {
  title: "Quranity",
  description: "Generated by Quranity app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
